{application,exflect,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,tools]},
              {description,"An inflection library for singularization/pluralization of English words."},
              {modules,['Elixir.Exflect','Elixir.Exflect.Detect',
                        'Elixir.Exflect.Ordinalize',
                        'Elixir.Exflect.Pluralize','Elixir.Exflect.Shared',
                        'Elixir.Exflect.Singularize',
                        'Elixir.Exflect.Support.TSV','Elixir.Exflect.Word',
                        'Elixir.String.Chars.Exflect.Word']},
              {registered,[]},
              {vsn,"1.0.0"}]}.
