{application,typed_ecto_schema,
             [{config_mtime,1744621395},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,ecto]},
              {description,"A library to define Ecto schemas with typespecs without all the boilerplate code."},
              {modules,['Elixir.TypedEctoSchema',
                        'Elixir.TypedEctoSchema.EctoTypeMapper',
                        'Elixir.TypedEctoSchema.SyntaxSugar',
                        'Elixir.TypedEctoSchema.TypeBuilder']},
              {registered,[]},
              {vsn,"0.4.1"}]}.
