{application,ecto_watch,
             [{config_mtime,1744621395},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,nimble_options,
                             postgrex,phoenix_pubsub,jason,ecto_sql]},
              {description,"EctoWatch allows you to easily get Phoenix.PubSub notifications directly from postgresql."},
              {modules,['Elixir.EctoWatch','Elixir.EctoWatch.Helpers',
                        'Elixir.EctoWatch.Options',
                        'Elixir.EctoWatch.Options.WatcherOptions',
                        'Elixir.EctoWatch.Options.WatcherOptions.SchemaDefinition',
                        'Elixir.EctoWatch.TestRepo',
                        'Elixir.EctoWatch.WatcherServer',
                        'Elixir.EctoWatch.WatcherSupervisor',
                        'Elixir.EctoWatch.WatcherTriggerValidator',
                        'Elixir.EctoWatch.WatcherTriggerValidator.FunctionDetails',
                        'Elixir.EctoWatch.WatcherTriggerValidator.TriggerDetails']},
              {registered,[]},
              {vsn,"0.13.1"}]}.
